/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_JNIBase */

#ifndef _Included_es_gva_cit_jmrsid_JNIBase
#define _Included_es_gva_cit_jmrsid_JNIBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getIndexCountNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getIndexCountNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    initializeNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_initializeNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getNumLevelsNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getNumLevelsNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getWidthNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getWidthNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getHeightNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getHeightNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getStripHeightNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getStripHeightNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getNumBandsNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getNumBandsNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getColorSpaceNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getColorSpaceNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_JNIBase
 * Method:    getDataTypeNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_JNIBase_getDataTypeNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
