/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTIScene */

#ifndef _Included_es_gva_cit_jmrsid_LTIScene
#define _Included_es_gva_cit_jmrsid_LTIScene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_LTIScene
 * Method:    LTISceneNat
 * Signature: (DDDDD)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTIScene_LTISceneNat
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     es_gva_cit_jmrsid_LTIScene
 * Method:    FreeLTISceneNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTIScene_FreeLTISceneNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
