/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTIPixel */

#ifndef _Included_es_gva_cit_jmrsid_LTIPixel
#define _Included_es_gva_cit_jmrsid_LTIPixel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_LTIPixel
 * Method:    LTIPixelNat
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTIPixel_LTIPixelNat
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     es_gva_cit_jmrsid_LTIPixel
 * Method:    FreeLTIPixelNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTIPixel_FreeLTIPixelNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
