/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTIUtils */

#ifndef _Included_es_gva_cit_jmrsid_LTIUtils
#define _Included_es_gva_cit_jmrsid_LTIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_LTIUtils
 * Method:    levelToMagNat
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_es_gva_cit_jmrsid_LTIUtils_levelToMagNat
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_gva_cit_jmrsid_LTIUtils
 * Method:    FreeLTIUtilsNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTIUtils_FreeLTIUtilsNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
