/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_MrSIDImageReaderBase */

#ifndef _Included_es_gva_cit_jmrsid_MrSIDImageReaderBase
#define _Included_es_gva_cit_jmrsid_MrSIDImageReaderBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_MrSIDImageReaderBase
 * Method:    FreeMrSIDImageReaderBaseNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_MrSIDImageReaderBase_FreeMrSIDImageReaderBaseNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
