/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTISceneBuffer */

#ifndef _Included_es_gva_cit_jmrsid_LTISceneBuffer
#define _Included_es_gva_cit_jmrsid_LTISceneBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_LTISceneBuffer
 * Method:    LTISceneBufferNat
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTISceneBuffer_LTISceneBufferNat
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     es_gva_cit_jmrsid_LTISceneBuffer
 * Method:    LTISceneBuffer1Nat
 * Signature: (JIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTISceneBuffer_LTISceneBuffer1Nat
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     es_gva_cit_jmrsid_LTISceneBuffer
 * Method:    FreeLTISceneBufferNat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTISceneBuffer_FreeLTISceneBufferNat
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
