/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTIImage */

#ifndef _Included_es_gva_cit_jmrsid_LTIImage
#define _Included_es_gva_cit_jmrsid_LTIImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getMetadataNat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTIImage_getMetadataNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getDimsAtMagWidthNat
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIImage_getDimsAtMagWidthNat
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getDimsAtMagHeightNat
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIImage_getDimsAtMagHeightNat
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getPixelPropsNat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTIImage_getPixelPropsNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getBackgroundPixelNat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTIImage_getBackgroundPixelNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getNoDataPixelNat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_es_gva_cit_jmrsid_LTIImage_getNoDataPixelNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getGeoCoordNat
 * Signature: (JLes/gva/cit/jmrsid/LTIGeoCoord;)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIImage_getGeoCoordNat
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    FreeLTIImageNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTIImage_FreeLTIImageNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getMinMagnificationNat
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_es_gva_cit_jmrsid_LTIImage_getMinMagnificationNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIImage
 * Method:    getMaxMagnificationNat
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_es_gva_cit_jmrsid_LTIImage_getMaxMagnificationNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
