/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTIMetadataRecord */

#ifndef _Included_es_gva_cit_jmrsid_LTIMetadataRecord
#define _Included_es_gva_cit_jmrsid_LTIMetadataRecord
#ifdef __cplusplus
extern "C" {
#endif
#undef es_gva_cit_jmrsid_LTIMetadataRecord_LTI_METADATA_DATATYPE_INT
#define es_gva_cit_jmrsid_LTIMetadataRecord_LTI_METADATA_DATATYPE_INT 0L
#undef es_gva_cit_jmrsid_LTIMetadataRecord_LTI_METADATA_DATATYPE_FLOAT
#define es_gva_cit_jmrsid_LTIMetadataRecord_LTI_METADATA_DATATYPE_FLOAT 1L
#undef es_gva_cit_jmrsid_LTIMetadataRecord_LTI_METADATA_DATATYPE_STRING
#define es_gva_cit_jmrsid_LTIMetadataRecord_LTI_METADATA_DATATYPE_STRING 2L
/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getTagNameNat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getTagNameNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    isScalarNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_isScalarNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    isVectorNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_isVectorNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    isArrayNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_isArrayNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getDataTypeNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getDataTypeNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getScalarDataNat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getScalarDataNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getVectorDataNat
 * Signature: (J)Les/gva/cit/jmrsid/StringArray;
 */
JNIEXPORT jobject JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getVectorDataNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getArrayDataNat
 * Signature: (J)Les/gva/cit/jmrsid/StringArray;
 */
JNIEXPORT jobject JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getArrayDataNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getNumDimsNat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getNumDimsNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    getDimsNat
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_getDimsNat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_gva_cit_jmrsid_LTIMetadataRecord
 * Method:    FreeLTIMetadataRecordNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTIMetadataRecord_FreeLTIMetadataRecordNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
