/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_gva_cit_jmrsid_LTIImageStage */

#ifndef _Included_es_gva_cit_jmrsid_LTIImageStage
#define _Included_es_gva_cit_jmrsid_LTIImageStage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_gva_cit_jmrsid_LTIImageStage
 * Method:    readNat
 * Signature: (JJJJLes/gva/cit/jmrsid/LTISceneBuffer;)I
 */
JNIEXPORT jint JNICALL Java_es_gva_cit_jmrsid_LTIImageStage_readNat
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     es_gva_cit_jmrsid_LTIImageStage
 * Method:    FreeLTIImageStageNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_gva_cit_jmrsid_LTIImageStage_FreeLTIImageStageNat
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
