/*
 * This file is generated by IncBuildNumber.ksh
 * Change only the major version, or build number if you are editing manually.
 * last updated: Tue Jan 25 13:22:24 2005

 */
#define NCS_VERSION_NUMBER 3,1,0,163
#define NCS_VERSION_STRING "3,1,0,163\0"
#define NCS_VERSION_STRING_NO_NULL "3,1,0,163"
#define NCS_VERSION_STRING_DOT_DEL "3.1.0.163"
#define NCS_SERVER_VERSION_NUMBER 3.1
#define NCS_SERVER_VERSION_STRING "3.1"
#define NCS_ECWSDK_VERSION_NUMBER 2.5
#define NCS_ECWSDK_VERSION_STRING "2.5"
#define NCS_HEADEREDITOR_VERSION_NUMBER 2.52
#define NCS_HEADEREDITOR_VERSION_STRING "2.52"
