/*
 * OdMatrixControlPanel.java
 *
 * Created on 20 de octubre de 2008, 13:19
 */

package org.gvsig.graph.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.gvsig.exceptions.BaseException;
import org.gvsig.fmap.util.LayerListCellRenderer;
import org.gvsig.graph.IODMatrixFileWriter;
import org.gvsig.graph.ODMatrixExtension;

import com.iver.andami.PluginServices;
import com.iver.andami.ui.mdiManager.IWindow;
import com.iver.andami.ui.mdiManager.WindowInfo;
import com.iver.cit.gvsig.fmap.MapContext;
import com.iver.cit.gvsig.fmap.core.FShape;
import com.iver.cit.gvsig.fmap.layers.FLayer;
import com.iver.cit.gvsig.fmap.layers.FLayers;
import com.iver.cit.gvsig.fmap.layers.FLyrVect;
import com.iver.cit.gvsig.fmap.layers.LayersIterator;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import java.awt.Font;

/**
 * 
 * @author Fjp
 */
public class OdMatrixControlPanel extends JPanel implements IWindow {

	public static int TIME_SECONDS = 0;
	public static int TIME_MINUTES = 1;
	public static int LENGTH_METERS = 0;
	public static int LENGTH_KILOMETERS = 1;
	public static int LENGTH_YARDS = 2;
	public static int LENGTH_MILES = 3;
	public static int FILE_FORMAT_2_COLS = 0;
	public static int FILE_FORMAT_MANY_COLS = 1;

	private MapContext mapContext;
	
	private DefaultComboBoxModel cboLayerOriginsModel;
	private DefaultComboBoxModel cboLayerDestinationsModel;

	private WindowInfo wi;
	private boolean okPressed = false;

	/**
	 * This method initializes txtTolerance	
	 * 	
	 * @return javax.swing.JTextField	
	 */
	private JTextField getTxtTolerance() {
		if (txtTolerance == null) {
			txtTolerance = new JTextField();
			txtTolerance.setBounds(new Rectangle(159, 118, 94, 22));
			txtTolerance.setText("50");
		}
		return txtTolerance;
	}

	/**
	 * This method initializes txtFormatAreaDescription	
	 * 	
	 * @return javax.swing.JTextArea	
	 */
	private JTextArea getTxtFormatAreaDescription() {
		if (txtFormatAreaDescription == null) {
			txtFormatAreaDescription = new JTextArea();
			txtFormatAreaDescription.setBounds(new Rectangle(16, 55, 438, 53));
			txtFormatAreaDescription.setRows(3);
			txtFormatAreaDescription.setFont(new Font("Arial", Font.PLAIN, 10));
			txtFormatAreaDescription.setLineWrap(true);
			txtFormatAreaDescription.setEditable(false);
		}
		return txtFormatAreaDescription;
	}

	public static void main(String[] args) throws ClassNotFoundException,
			InstantiationException, IllegalAccessException {
		try {

			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (UnsupportedLookAndFeelException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		OdMatrixControlPanel panel = new OdMatrixControlPanel();
		JFrame test = new JFrame();

		test.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		test.add(panel);
		test.setBounds(panel.getBounds());
		test.setVisible(true);
	}

	/** Creates new form OdMatrixControlPanel */
	public OdMatrixControlPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLblToleranceUnits = new JLabel();
		jLblToleranceUnits.setBounds(new Rectangle(265, 118, 135, 20));
		jLblToleranceUnits.setText(_T("meters"));
		jLblTolerance = new JLabel();
		jLblTolerance.setBounds(new Rectangle(17, 118, 135, 20));
		jLblTolerance.setText(_T("Tolerance") + ":");
		jLblTolerance.setHorizontalAlignment(SwingConstants.RIGHT);
		this.setLayout(null);
		this.setSize(new Dimension(499, 350));
		jPanel1 = new javax.swing.JPanel();
		cboFileFormat = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		cboLayerOrigins = new javax.swing.JComboBox();
		jLblLayerOrigins = new javax.swing.JLabel();
		cboLayerDestinations = new javax.swing.JComboBox();
		jLblLayerDestinations = new javax.swing.JLabel();
		jLblFile = new javax.swing.JLabel();
		txtGeneratedFile = new javax.swing.JTextField();
		btnSelectFile = new javax.swing.JButton();
		btnOk = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();

		jPanel1.setLayout(null);
		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder(_T("Options")));

		jPanel1.setBounds(new Rectangle(14, 172, 468, 122));
		jPanel1.add(cboFileFormat, null);
		jPanel1.add(jLabel5, null);

		jPanel1.add(getTxtFormatAreaDescription(), null);
		IODMatrixFileWriter[] writers = ODMatrixExtension.getOdMatrixWriters();
		String[] formats = new String[writers.length];
		for (int i = 0; i < formats.length; i++) {
			formats[i] = _T(writers[i].getFormatDescription());
		}
		cboFileFormat.setModel(new DefaultComboBoxModel(formats));
		cboFileFormat.setSelectedIndex(0);

		cboFileFormat.setBounds(new Rectangle(158, 19, 295, 25));
		cboFileFormat.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent e) {
				System.out.println(e.getItem());
				
				txtFormatAreaDescription.setText(e.getItem().toString());
			}
		});
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel5.setBounds(new Rectangle(17, 22, 134, 16));
		jLabel5.setText(_T("File_Format") + ":");

		jPanel2.setLayout(null);

		// jPanel2.setLayout(new GridBagLayout(jPanel2, BoxLayout.Y_AXIS));
		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder(_T("Parameters")));

		jPanel2.setBounds(new Rectangle(14, 13, 468, 144));

		cboLayerOrigins.setBounds(new Rectangle(158, 32, 259, 22));
		jLblLayerOrigins
				.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLblLayerOrigins.setBounds(new Rectangle(17, 33, 135, 20));
		jLblLayerOrigins.setText(_T("Layer_Origins") + ":");

		cboLayerDestinations.setBounds(new Rectangle(158, 61, 259, 22));
		jLblLayerDestinations
				.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLblLayerDestinations.setBounds(new Rectangle(17, 59, 135, 20));
		jLblLayerDestinations.setText(_T("Layer_Destinations") + ":");

		jLblFile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLblFile.setBounds(new Rectangle(17, 90, 135, 20));
		jLblFile.setText(_T("Generated_File") + ":");

		txtGeneratedFile.setText("");

		txtGeneratedFile.setBounds(new Rectangle(159, 90, 259, 22));
		btnSelectFile.setText("...");

		btnSelectFile.setBounds(new Rectangle(425, 90, 28, 21));
		btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				JFileChooser dlg = new JFileChooser();
				if (dlg.showSaveDialog((Component) PluginServices.getMainFrame()) == JFileChooser.APPROVE_OPTION)
				{
					txtGeneratedFile.setText(dlg.getSelectedFile().getPath());
				}
			}
		});
		btnOk.setText(_T("OK"));
		btnOk.setBounds(new Rectangle(107, 305, 136, 26));
		btnOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOkActionPerformed(evt);
			}
		});

		btnCancel.setText(_T("Cancel"));
		btnCancel.setBounds(new Rectangle(257, 305, 136, 26));
		jPanel2.add(jLblLayerOrigins, null);
		jPanel2.add(cboLayerOrigins, null);
		jPanel2.add(jLblLayerDestinations, null);
		jPanel2.add(cboLayerDestinations, null);
		jPanel2.add(jLblFile, null);
		jPanel2.add(txtGeneratedFile, null);
		jPanel2.add(btnSelectFile, null);
		jPanel2.add(jLblTolerance, null);
		jPanel2.add(getTxtTolerance(), null);
		jPanel2.add(jLblToleranceUnits, null);
		this.add(jPanel2, null);
		this.add(jPanel1, null);
		this.add(btnOk, null);
		this.add(btnCancel, null);
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

	}// </editor-fold>

	private void closeWindow() {
		if (PluginServices.getMainFrame() != null) {
			PluginServices.getMDIManager().closeWindow(this);
		}
	}

	private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {
		if (getGeneratedFile().equalsIgnoreCase(""))
		{
			JOptionPane.showMessageDialog((Component) PluginServices.getMDIManager().getActiveWindow(),
					PluginServices.getText(null, "Please_select_a_valid_file"));
			return;
		}
		try {
			double tol = getTolerance();
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog((Component) PluginServices.getMDIManager().getActiveWindow(),
					PluginServices.getText(null, "Please_enter_a_valid_number"));
			return;
		}
		
		okPressed = true;
		closeWindow();
	}

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
		closeWindow();
	}
	
	/**
	 * @return Returns the okPressed.
	 */
	public boolean isOkPressed() {
		return okPressed;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOk;
	private javax.swing.JButton btnSelectFile;
	private javax.swing.JComboBox cboFileFormat;
	private javax.swing.JComboBox cboLayerDestinations;
	private javax.swing.JComboBox cboLayerOrigins;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLblFile;
	private javax.swing.JLabel jLblLayerDestinations;
	private javax.swing.JLabel jLblLayerOrigins;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField txtGeneratedFile;
	private JLabel jLblTolerance = null;
	private JTextField txtTolerance = null;
	private JLabel jLblToleranceUnits = null;
	private JTextArea txtFormatAreaDescription = null;

	// End of variables declaration

	public void setMapContext(MapContext mapContext) throws BaseException {
		this.mapContext = mapContext;
		FLayers layers = mapContext.getLayers();
		LayersIterator it = new LayersIterator(layers);
		Vector<FLyrVect> arrayLayers = new Vector<FLyrVect>();
		while (it.hasNext()) {
			FLayer lyr = it.nextLayer();
			if (!lyr.isAvailable())
				continue;
			if (lyr instanceof FLyrVect) {
				FLyrVect lyrVect = (FLyrVect) lyr;
				if ((lyrVect.getShapeType() == FShape.POINT)
						|| (lyrVect.getShapeType() == FShape.MULTIPOINT))
					arrayLayers.add(lyrVect);
					
			}
		}
		cboLayerOriginsModel = new DefaultComboBoxModel(arrayLayers);
		cboLayerDestinationsModel = new DefaultComboBoxModel(arrayLayers);
		cboLayerOrigins.setModel(cboLayerOriginsModel);
		cboLayerDestinations.setModel(cboLayerDestinationsModel);
		cboLayerOrigins.setRenderer(new LayerListCellRenderer());
		cboLayerDestinations.setRenderer(new LayerListCellRenderer());
		
	}

	public int getFileFormat() {
		return cboFileFormat.getSelectedIndex();
	}
	
	public String getGeneratedFile() {
		return txtGeneratedFile.getText();
	}
	
	public FLyrVect getOriginsLayer() {
		return (FLyrVect) cboLayerOrigins.getSelectedItem();
	}

	public FLyrVect getDestinationsLayer() {
		return (FLyrVect) cboLayerDestinations.getSelectedItem();
	}

	public WindowInfo getWindowInfo() {
		if (wi == null) {
			wi = new WindowInfo(WindowInfo.MODALDIALOG);
			wi.setWidth((int) this.getPreferredSize().getWidth());
			wi.setHeight((int) this.getPreferredSize().getHeight());
			wi.setTitle(_T("odmatrix_control_panel"));
		}
		return wi;
	}
	
	public Object getWindowProfile(){
		return WindowInfo.DIALOG_PROFILE;
	}

	public double getTolerance() {
		return Double.parseDouble(txtTolerance.getText());
	}
	
	private String _T(String str) {
		return PluginServices.getText(this, str);
	}

} // @jve:decl-index=0:visual-constraint="10,10"
