/*
 * TurnCostsTableChooser.java
 *
 * Created on __DATE__, __TIME__
 */

package org.gvsig.graph.gui;

import java.sql.Types;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

import com.iver.andami.PluginServices;
import com.iver.andami.ui.mdiManager.IWindow;
import com.iver.andami.ui.mdiManager.WindowInfo;
import com.iver.cit.gvsig.fmap.drivers.FieldDescription;
import com.iver.cit.gvsig.project.documents.table.ProjectTable;
import com.iver.utiles.NumberUtilities;

/**
 *
 * @author  __USER__
 */
public class TurnCostsTableChooser extends javax.swing.JPanel implements IWindow {

	private WindowInfo w;
	private boolean isOkSelected = false;
	private ProjectTable[]  tables;
		
	/** Creates new form TurnCostsTableChooser */
	public TurnCostsTableChooser() {
		initComponents();
	}
	
	public void setModel(ProjectTable[] tables) {
		this.tables = tables;
//		jLabel1.setText(_T("select_turn_costs_table"));
//		jLabel2.setText(_T("field_from_id"));
//		jLabel3.setText(_T("field_to_id"));
//		jLabel4.setText(_T("field_turn_costs"));
		ArrayList<String> tableNames = new ArrayList<String>();
		DefaultComboBoxModel cboModel = new DefaultComboBoxModel(tables);

		cboTable.setModel(cboModel);
		
		updateFieldCombos();
		
	}
	
	private void updateFieldCombos() {
		ProjectTable selectedTable = (ProjectTable) cboTable.getSelectedItem();
		if (selectedTable == null) {
			cboFieldIdFrom.setModel(new DefaultComboBoxModel());
			cboFieldIdTo.setModel(new DefaultComboBoxModel());
			cboFieldTurnCost.setModel(new DefaultComboBoxModel());
			return;
		}
		Vector numFields = new Vector();
		FieldDescription[] fields = selectedTable.getModelo().getFieldsDescription(); 
		for (int i=0; i < fields.length; i++) {
			if (NumberUtilities.isNumeric(fields[i].getFieldType()))
				numFields.add(fields[i].getFieldAlias());
		}
		cboFieldIdFrom.setModel(new DefaultComboBoxModel(numFields));
		cboFieldIdTo.setModel(new DefaultComboBoxModel(numFields));
		cboFieldTurnCost.setModel(new DefaultComboBoxModel(numFields));
	}

	public WindowInfo getWindowInfo() {
		if (w == null) {
			w = new WindowInfo(WindowInfo.MODALDIALOG | WindowInfo.RESIZABLE);
			w.setTitle(_T("TurnTable"));
			w.setWidth(360);
			w.setHeight(210);
		}
		return w;
	}

	public Object getWindowProfile() {
		return null;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		cboTable = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		cboFieldIdFrom = new javax.swing.JComboBox();
		cboFieldIdTo = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		cboFieldTurnCost = new javax.swing.JComboBox();
		btnOK = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();

		jLabel1.setText(_T("Table_with_turn_costs") + ":");

		cboTable.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		cboTable.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cboTableActionPerformed(evt);
			}
		});

		jLabel2.setText(_T("Field_with_From_ID") + ":");

		cboFieldIdFrom.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cboFieldIdTo.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel3.setText(_T("Field_with_To_ID") + ":");

		jLabel4.setText(_T("Field_with_turn_cost") + ":");

		cboFieldTurnCost.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnOK.setText(_T("OK"));
		btnOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOKActionPerformed(evt);
			}
		});

		btnCancel.setText(_T("Cancel"));
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								false)
																						.add(
																								jLabel4,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								jLabel3,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								jLabel2,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								jLabel1,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								cboFieldTurnCost,
																								0,
																								224,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								cboFieldIdTo,																								
																								0,
																								224,
																								Short.MAX_VALUE
																								)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								cboTable,
																								0,
																								224,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								cboFieldIdFrom,
																								0,
																								224,
																								Short.MAX_VALUE)))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				btnOK)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				btnCancel)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel1)
														.add(
																cboTable,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel2)
														.add(
																cboFieldIdFrom,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																cboFieldIdTo,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel3))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																cboFieldTurnCost,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel4))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												17, Short.MAX_VALUE)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(btnCancel)
														.add(btnOK))
										.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
		if (PluginServices.getMainFrame() != null)
			PluginServices.getMDIManager().closeWindow(this);

	}

	private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {
		isOkSelected  = true;
		if (PluginServices.getMainFrame() != null)
			PluginServices.getMDIManager().closeWindow(this);
	}

	private void cboTableActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("Seleccionado:" + cboTable.getSelectedItem());
		updateFieldCombos();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOK;
	private javax.swing.JComboBox cboFieldIdFrom;
	private javax.swing.JComboBox cboFieldIdTo;
	private javax.swing.JComboBox cboFieldTurnCost;
	private javax.swing.JComboBox cboTable;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	// End of variables declaration//GEN-END:variables

	public boolean isOkSelected() {
		return isOkSelected;
	}
	
	public ProjectTable getSelectedTable() {
		return (ProjectTable) cboTable.getSelectedItem();
	}
	
	public String getFieldFromId() {
		return (String) cboFieldIdFrom.getSelectedItem();
	}
	public String getFieldToId() {
		return (String) cboFieldIdTo.getSelectedItem();
	}
	public String getFieldTurnCost() {
		return (String) cboFieldTurnCost.getSelectedItem();
	}
	
	private String _T(String str) {
		return PluginServices.getText(this, str);
	}


}